"""Core entity models for campaign state.

These dataclasses are intentionally provider-agnostic so game logic,
model providers, and persistence can evolve independently.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from typing import Any


@dataclass
class Character:
    """Represents a player-controlled character."""

    id: str
    name: str
    char_class: str
    level: int = 1
    hp: int = 20
    max_hp: int = 20
    armor_class: int = 12
    attack_bonus: int = 3
    inventory: list[str] = field(default_factory=list)
    xp: int = 0
    equipped_item_id: str | None = None


@dataclass
class NPC:
    """Represents a non-player character and relationship state."""

    id: str
    name: str
    location_id: str
    disposition: int = 0
    notes: list[str] = field(default_factory=list)
    relationships: dict[str, int] = field(default_factory=dict)


@dataclass
class Location:
    """Represents a world location."""

    id: str
    name: str
    description: str
    connections: list[str] = field(default_factory=list)


@dataclass
class Quest:
    """Represents a quest and completion state."""

    id: str
    title: str
    description: str
    status: str = "active"
    objectives: list[str] = field(default_factory=list)


@dataclass
class CampaignSettings:
    """Configurable campaign behavior toggles."""

    @dataclass
    class ContentSettings:
        """Narration-layer content controls configured per campaign."""

        tone: str = "heroic"
        maturity_level: str = "standard"
        thematic_flags: list[str] = field(default_factory=lambda: ["adventure", "mystery"])

    profile: str = "classic_fantasy"
    mature_content_enabled: bool = False
    narration_tone: str = "heroic"
    image_generation_enabled: bool = False
    content_settings: ContentSettings = field(default_factory=ContentSettings)


@dataclass
class CampaignState:
    """Top-level persistent campaign state."""

    campaign_id: str
    campaign_name: str
    turn_count: int
    current_location_id: str
    player: Character
    npcs: dict[str, NPC]
    locations: dict[str, Location]
    quests: dict[str, Quest]
    world_flags: dict[str, bool] = field(default_factory=dict)
    active_enemy_id: str | None = None
    active_enemy_hp: int | None = None
    active_dialogue_npc_id: str | None = None
    active_dialogue_node_id: str | None = None
    event_log: list[str] = field(default_factory=list)
    settings: CampaignSettings = field(default_factory=CampaignSettings)

    def to_dict(self) -> dict[str, Any]:
        """Serialize campaign state to a dictionary for JSON storage."""

        return asdict(self)

    @classmethod
    def from_dict(cls, payload: dict[str, Any]) -> "CampaignState":
        """Deserialize from JSON payload.

        Assumes payload shape generated by `to_dict`.
        """

        return cls(
            campaign_id=payload["campaign_id"],
            campaign_name=payload["campaign_name"],
            turn_count=payload["turn_count"],
            current_location_id=payload["current_location_id"],
            player=Character(**payload["player"]),
            npcs={k: NPC(**v) for k, v in payload["npcs"].items()},
            locations={k: Location(**v) for k, v in payload["locations"].items()},
            quests={k: Quest(**v) for k, v in payload["quests"].items()},
            world_flags={k: bool(v) for k, v in payload.get("world_flags", {}).items()},
            active_enemy_id=payload.get("active_enemy_id"),
            active_enemy_hp=payload.get("active_enemy_hp"),
            active_dialogue_npc_id=payload.get("active_dialogue_npc_id"),
            active_dialogue_node_id=payload.get("active_dialogue_node_id"),
            event_log=payload.get("event_log", []),
            settings=cls._settings_from_payload(payload.get("settings", {})),
        )

    @staticmethod
    def _settings_from_payload(raw_settings: dict[str, Any]) -> CampaignSettings:
        """Deserialize settings while preserving backward compatibility."""

        settings = dict(raw_settings)
        raw_content = settings.pop("content_settings", None)
        content_settings: CampaignSettings.ContentSettings

        if raw_content is None:
            content_settings = CampaignSettings.ContentSettings(
                tone=settings.get("narration_tone", "heroic"),
                maturity_level="mature" if settings.get("mature_content_enabled") else "standard",
            )
        else:
            content_settings = CampaignSettings.ContentSettings(
                tone=raw_content.get("tone", settings.get("narration_tone", "heroic")),
                maturity_level=raw_content.get(
                    "maturity_level", "mature" if settings.get("mature_content_enabled") else "standard"
                ),
                thematic_flags=list(raw_content.get("thematic_flags", ["adventure", "mystery"])),
            )

        settings["content_settings"] = content_settings
        return CampaignSettings(**settings)
